name: Sync to S3
on:
  push:
    branches:
      - feature/CI
    paths:
      - 'scripts/**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Sync to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
        bucket: taehun-s3-bucket-230717
        dir: './scripts'
      env:
        AWS_S3_BUCKET: 'taehun-s3-bucket-230717'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-northeast-2'
